/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.operations;

import com.self.openapi.pokemon.utils.Options;
import com.self.openapi.pokemon.utils.RetryConfig;
import com.self.openapi.pokemon.utils.Utils;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

public class GenerationListRequestBuilder {

    private Optional<Long> limit = Optional.empty();
    private Optional<Long> offset = Optional.empty();
    private Optional<String> q = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGenerationList sdk;

    public GenerationListRequestBuilder(SDKMethodInterfaces.MethodCallGenerationList sdk) {
        this.sdk = sdk;
    }
                
    public GenerationListRequestBuilder limit(long limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = Optional.of(limit);
        return this;
    }

    public GenerationListRequestBuilder limit(Optional<Long> limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = limit;
        return this;
    }
                
    public GenerationListRequestBuilder offset(long offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = Optional.of(offset);
        return this;
    }

    public GenerationListRequestBuilder offset(Optional<Long> offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = offset;
        return this;
    }
                
    public GenerationListRequestBuilder q(String q) {
        Utils.checkNotNull(q, "q");
        this.q = Optional.of(q);
        return this;
    }

    public GenerationListRequestBuilder q(Optional<String> q) {
        Utils.checkNotNull(q, "q");
        this.q = q;
        return this;
    }
                
    public GenerationListRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public GenerationListRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public GenerationListResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.listGenerations(
            limit,
            offset,
            q,
            options);
    }
}
