/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.self.openapi.pokemon.models.components.PokemonDetail;
import com.self.openapi.pokemon.utils.Response;
import com.self.openapi.pokemon.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class PokemonRetrieveByIdOrNameResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    private Optional<? extends PokemonDetail> pokemonDetail;

    @JsonCreator
    public PokemonRetrieveByIdOrNameResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PokemonDetail> pokemonDetail) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(pokemonDetail, "pokemonDetail");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.pokemonDetail = pokemonDetail;
    }
    
    public PokemonRetrieveByIdOrNameResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PokemonDetail> pokemonDetail() {
        return (Optional<PokemonDetail>) pokemonDetail;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public PokemonRetrieveByIdOrNameResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public PokemonRetrieveByIdOrNameResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PokemonRetrieveByIdOrNameResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    public PokemonRetrieveByIdOrNameResponse withPokemonDetail(PokemonDetail pokemonDetail) {
        Utils.checkNotNull(pokemonDetail, "pokemonDetail");
        this.pokemonDetail = Optional.ofNullable(pokemonDetail);
        return this;
    }

    public PokemonRetrieveByIdOrNameResponse withPokemonDetail(Optional<? extends PokemonDetail> pokemonDetail) {
        Utils.checkNotNull(pokemonDetail, "pokemonDetail");
        this.pokemonDetail = pokemonDetail;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PokemonRetrieveByIdOrNameResponse other = (PokemonRetrieveByIdOrNameResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.pokemonDetail, other.pokemonDetail);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            pokemonDetail);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PokemonRetrieveByIdOrNameResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "pokemonDetail", pokemonDetail);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends PokemonDetail> pokemonDetail = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        public Builder pokemonDetail(PokemonDetail pokemonDetail) {
            Utils.checkNotNull(pokemonDetail, "pokemonDetail");
            this.pokemonDetail = Optional.ofNullable(pokemonDetail);
            return this;
        }

        public Builder pokemonDetail(Optional<? extends PokemonDetail> pokemonDetail) {
            Utils.checkNotNull(pokemonDetail, "pokemonDetail");
            this.pokemonDetail = pokemonDetail;
            return this;
        }
        
        public PokemonRetrieveByIdOrNameResponse build() {
            return new PokemonRetrieveByIdOrNameResponse(
                contentType,
                statusCode,
                rawResponse,
                pokemonDetail);
        }
    }
}

