/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.operations;

import com.self.openapi.pokemon.utils.Options;
import com.self.openapi.pokemon.utils.RetryConfig;
import com.self.openapi.pokemon.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PokemonRetrieveByIdOrNameRequestBuilder {

    private String id;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPokemonRetrieveByIdOrName sdk;

    public PokemonRetrieveByIdOrNameRequestBuilder(SDKMethodInterfaces.MethodCallPokemonRetrieveByIdOrName sdk) {
        this.sdk = sdk;
    }

    public PokemonRetrieveByIdOrNameRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
                
    public PokemonRetrieveByIdOrNameRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PokemonRetrieveByIdOrNameRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PokemonRetrieveByIdOrNameResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.getByIdOrName(
            id,
            options);
    }
}
