/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.operations;

import com.self.openapi.pokemon.utils.Options;
import com.self.openapi.pokemon.utils.RetryConfig;
import com.self.openapi.pokemon.utils.Utils;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

public class PokemonListRequestBuilder {

    private Optional<Long> limit = Optional.empty();
    private Optional<Long> offset = Optional.empty();
    private Optional<String> q = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPokemonList sdk;

    public PokemonListRequestBuilder(SDKMethodInterfaces.MethodCallPokemonList sdk) {
        this.sdk = sdk;
    }
                
    public PokemonListRequestBuilder limit(long limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = Optional.of(limit);
        return this;
    }

    public PokemonListRequestBuilder limit(Optional<Long> limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = limit;
        return this;
    }
                
    public PokemonListRequestBuilder offset(long offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = Optional.of(offset);
        return this;
    }

    public PokemonListRequestBuilder offset(Optional<Long> offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = offset;
        return this;
    }
                
    public PokemonListRequestBuilder q(String q) {
        Utils.checkNotNull(q, "q");
        this.q = Optional.of(q);
        return this;
    }

    public PokemonListRequestBuilder q(Optional<String> q) {
        Utils.checkNotNull(q, "q");
        this.q = q;
        return this;
    }
                
    public PokemonListRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PokemonListRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public PokemonListResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.list(
            limit,
            offset,
            q,
            options);
    }
}
