/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.self.openapi.pokemon.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class PaginatedGenerationSummaryList {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("count")
    private Optional<Long> count;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("next")
    private JsonNullable<String> next;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous")
    private JsonNullable<String> previous;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("results")
    private Optional<? extends List<GenerationSummary>> results;

    @JsonCreator
    public PaginatedGenerationSummaryList(
            @JsonProperty("count") Optional<Long> count,
            @JsonProperty("next") JsonNullable<String> next,
            @JsonProperty("previous") JsonNullable<String> previous,
            @JsonProperty("results") Optional<? extends List<GenerationSummary>> results) {
        Utils.checkNotNull(count, "count");
        Utils.checkNotNull(next, "next");
        Utils.checkNotNull(previous, "previous");
        Utils.checkNotNull(results, "results");
        this.count = count;
        this.next = next;
        this.previous = previous;
        this.results = results;
    }
    
    public PaginatedGenerationSummaryList() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty());
    }

    @JsonIgnore
    public Optional<Long> count() {
        return count;
    }

    @JsonIgnore
    public JsonNullable<String> next() {
        return next;
    }

    @JsonIgnore
    public JsonNullable<String> previous() {
        return previous;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<GenerationSummary>> results() {
        return (Optional<List<GenerationSummary>>) results;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public PaginatedGenerationSummaryList withCount(long count) {
        Utils.checkNotNull(count, "count");
        this.count = Optional.ofNullable(count);
        return this;
    }

    public PaginatedGenerationSummaryList withCount(Optional<Long> count) {
        Utils.checkNotNull(count, "count");
        this.count = count;
        return this;
    }

    public PaginatedGenerationSummaryList withNext(String next) {
        Utils.checkNotNull(next, "next");
        this.next = JsonNullable.of(next);
        return this;
    }

    public PaginatedGenerationSummaryList withNext(JsonNullable<String> next) {
        Utils.checkNotNull(next, "next");
        this.next = next;
        return this;
    }

    public PaginatedGenerationSummaryList withPrevious(String previous) {
        Utils.checkNotNull(previous, "previous");
        this.previous = JsonNullable.of(previous);
        return this;
    }

    public PaginatedGenerationSummaryList withPrevious(JsonNullable<String> previous) {
        Utils.checkNotNull(previous, "previous");
        this.previous = previous;
        return this;
    }

    public PaginatedGenerationSummaryList withResults(List<GenerationSummary> results) {
        Utils.checkNotNull(results, "results");
        this.results = Optional.ofNullable(results);
        return this;
    }

    public PaginatedGenerationSummaryList withResults(Optional<? extends List<GenerationSummary>> results) {
        Utils.checkNotNull(results, "results");
        this.results = results;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaginatedGenerationSummaryList other = (PaginatedGenerationSummaryList) o;
        return 
            Objects.deepEquals(this.count, other.count) &&
            Objects.deepEquals(this.next, other.next) &&
            Objects.deepEquals(this.previous, other.previous) &&
            Objects.deepEquals(this.results, other.results);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            count,
            next,
            previous,
            results);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaginatedGenerationSummaryList.class,
                "count", count,
                "next", next,
                "previous", previous,
                "results", results);
    }
    
    public final static class Builder {
 
        private Optional<Long> count = Optional.empty();
 
        private JsonNullable<String> next = JsonNullable.undefined();
 
        private JsonNullable<String> previous = JsonNullable.undefined();
 
        private Optional<? extends List<GenerationSummary>> results = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder count(long count) {
            Utils.checkNotNull(count, "count");
            this.count = Optional.ofNullable(count);
            return this;
        }

        public Builder count(Optional<Long> count) {
            Utils.checkNotNull(count, "count");
            this.count = count;
            return this;
        }

        public Builder next(String next) {
            Utils.checkNotNull(next, "next");
            this.next = JsonNullable.of(next);
            return this;
        }

        public Builder next(JsonNullable<String> next) {
            Utils.checkNotNull(next, "next");
            this.next = next;
            return this;
        }

        public Builder previous(String previous) {
            Utils.checkNotNull(previous, "previous");
            this.previous = JsonNullable.of(previous);
            return this;
        }

        public Builder previous(JsonNullable<String> previous) {
            Utils.checkNotNull(previous, "previous");
            this.previous = previous;
            return this;
        }

        public Builder results(List<GenerationSummary> results) {
            Utils.checkNotNull(results, "results");
            this.results = Optional.ofNullable(results);
            return this;
        }

        public Builder results(Optional<? extends List<GenerationSummary>> results) {
            Utils.checkNotNull(results, "results");
            this.results = results;
            return this;
        }
        
        public PaginatedGenerationSummaryList build() {
            return new PaginatedGenerationSummaryList(
                count,
                next,
                previous,
                results);
        }
    }
}

