/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.self.openapi.pokemon.models.components;

public class Security {
    // Security not configured but we create this class 
    // to help with SecuritySource references in sdk hook context
}